services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - TWENTY_CRM_URL=${TWENTY_CRM_URL}
      - TWENTY_API_KEY=${TWENTY_API_KEY}
      - REDIS_URL=redis://redis:6389
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6389:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: